const notificationstypes = {
  CREATE_NOTIFICATION_START: "CREATE_NOTIFICATION_START",
  DELETE_NOTIFICATION_START: "DELETE_NOTIFICATION_START",
  FETCH_USER_NOTIFICATION_START: "FETCH_USER_NOTIFICATION_START",
  SET_USER_NOTIFICATION_START: "SET_USER_NOTIFICATION_START",
};

export default notificationstypes;
