const searchTypes = {
  //   SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  //   SEARCH_REQUESTS: "SEARCH_REQUESTS",
  START_SEARCH: "START_SEARCH",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
};

export default searchTypes;
