const requestsTypes = {
  ADD_NEW_REQUEST_START: "ADD_NEW_REQUEST_START",
  FETCH_REQUESTS_START: "FETCH_REQUESTS_START",
  FETCH_USER_REQUESTS: "FETCH_USER_REQUESTS",
  SET_REQUESTS: "SET_REQUESTS",
  DELETE_REQUEST_START: "DELETE_REQUEST_START",
  FETCH_REQUEST_START: "FETCH_REQUEST_START",
  FETCH_REC_REQUESTS: "FETCH_REC_REQUESTS",
  SET_REQUEST: "SET_REQUEST",
  SET_USER_REQUESTS: "SET_USER_REQUESTS",
  INCREMENT_REQUEST_VIEW: "INCREMENT_REQUEST_VIEW",
  SET_REC_REQUESTS: "SET_REC_REQUESTS",
  // ADD_NEW_USER_REQUEST_START: "ADD_NEW_USER_REQUEST_START",
};

export default requestsTypes;
