const productsTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_USER_PRODUCTS: "FETCH_USER_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  FETCH_REC_PRODUCTS: "FETCH_REC_PRODUCTS",
  SET_PRODUCT: "SET_PRODUCT",
  SET_USER_PRODUCTS: "SET_USER_PRODUCTS",
  SET_REC_PRODUCTS: "SET_REC_PRODUCTS",
};

export default productsTypes;
