const auctionTypes = {
  ADD_NEW_AUCTION_START: "ADD_NEW_AUCTION_START",
  DELETE_AUCTION_START: "DELETE_AUCTION_START",
  RESOLVE_AUCTION_START: "RESOLVE_AUCTION_START",
  FETCH_AUCTIONS_START: "FETCH_AUCTIONS_START",
  FETCH_AUCTION_START: "FETCH_AUCTION_START",
  FETCH_USER_AUCTIONS: "FETCH_USER_AUCTIONS",
  FETCH_REC_AUCTIONS: "FETCH_REC_PRODUCTS",
  FETCH_HOMEPAGE_AUCTIONS: "FETCH_HOMEPAGE_AUCTIONS",
  SET_AUCTIONS_START: "SET_AUCTIONS_START",
  SET_AUCTION_START: "SET_AUCTION_START",
  SET_USER_AUCTIONS: "SET_USER_AUCTIONS",
  SET_REC_AUCTIONS: "SET_REC_PRODUCTS",
  SET_HOMEPAGE_AUCTIONS: "SET_HOMEPAGE_AUCTIONS",
};

export default auctionTypes;
